[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
<<<<<<< HEAD
clap = { version = "4.5.48", features = ["derive"] } # A simple to use, efficient, and full-featured Command Line Argument Parser
=======
clap = { version = "4.5.48", features = ["derive"] }
>>>>>>> 60140142408b8793ce5f6262fa6cd790a8379f23
